return {
    "nvim-treesitter/nvim-treesitter",
    event = { "BufReadPre", "BufNewFile" },
    build = ":TSUpdate",
    dependencies = {
        "windwp/nvim-ts-autotag",
    },
    config = function()
        local treesitter = require("nvim-treesitter.configs")

        treesitter.setup({
            highlight = {
                enable = true,
            },
            indent = {
                enable = true,
            },
            autotag = {
                enable = true,
            },
            ensure_installed = {
                "angular",
                "asm",
                "astro",
                "bash",
                "c",
                "c_sharp",
                "cmake",
                "cpp",
                "css",
                "csv",
                "dart",
                "dockerfile",
                "doxygen",
                "editorconfig",
                "elixir",
                "erlang",
                "git_config",
                "git_rebase",
                "gitattributes",
                "gitcommit",
                "gitignore",
                "gleam",
                "go",
                "gomod",
                "gosum",
                "gowork",
                "graphql",
                "groovy",
                "haskell",
                "html",
                "htmldjango",
                "ini",
                "java",
                "javascript",
                "jsdoc",
                "json",
                "json5",
                "jsonc",
                -- "julia",
                "kotlin",
                "llvm",
                "lua",
                "luadoc",
                "lua_patterns",
                "luau",
                "make",
                "markdown",
                "markdown_inline",
                "nim",
                "nim_format_string",
                "ninja",
                "nix",
                -- "ocaml",
                -- "ocaml_interface",
                -- "ocamllex",
                -- "perl",
                -- "php",
                -- "phpdoc",
                "prisma",
                "properties",
                "proto",
                "python",
                "r",
                "regex",
                "robots",
                "ruby",
                "rust",
                -- "scala",
                "scala",
                "sql",
                "svelte",
                -- "swift",
                "tmux",
                "todotext",
                "toml",
                "tsx",
                "typescript",
                "vim",
                "vimdoc",
                "vue",
                "xml",
                "yaml",
                "zig",
            },
            incremental_selection = {
                enable = true,
                keymaps = {
                    init_selection = "<C-space>",
                    node_incremental = "<C-space>",
                    scope_incremental = false,
                    node_decremental = "<bs>",
                },
            },
        })
    end,
}
